@startuml

class Post {
        - Integer id
        - Date postTime
        - Date lastCommentTime
        - String title
        - String content
}

enum CommentType {
        TO_POST,
        TO_COMMENT
}

class Comment {
        - Integer commentId
        - CommentType type
        - Integer receiverId
        - Integer authorId
        - String content
        - Integer postId
        - Date timeStamp
}

class Notification {
        - Integer id
        - Integer userId
        - Date time
        - Integer commentId
        - Boolean hasViewed
}

@enduml
