@startuml

class Post {
        - Integer id
        - Date postTime
        - Date lastCommentTime
        - String title
        - String content

        + (getters...)
        + (setters...)
}

class Notification {
        - Integer id
        - Integer userId
        - Date time
        - Integer commentId
        - Boolean hasViewed
}

@enduml
